# Generated by Django 3.2.25 on 2024-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=' shop/static/shop/img/product/%Y/%m/%d'),
        ),
    ]
